apiVersion: v1
kind: Service
metadata:
  name: drone-app-mysql
  labels:
    app: drone-app
spec:
  ports:
    - port: 3306
  selector:
    app: drone-app
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: drone-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1 # for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: drone-app-mysql
  labels:
    app: drone-app
spec:
  selector:
    matchLabels:
      app: drone-app
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: drone-app
        tier: mysql
    spec:
      containers:
      - image: evandroborzi/drone-app-mysql:v1
        name: mysql
        env:
        - name: "MYSQL_USER"
          value: "user"
        - name: "MYSQL_PASSWORD"
          value: "password"
        - name: "MYSQL_DATABASE"
          value: "mysql"
        - name: "MYSQL_ROOT_PASSWORD"
          value: "password"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim